"""add_password_reset_tokens

Revision ID: 334e212b2ba3
Revises: 97f4645ef2c0
Create Date: 2026-06-08 09:40:13.086821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '334e212b2ba3'
down_revision: Union[str, None] = '97f4645ef2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_ai_insights_project_id', table_name='ai_insights')
    op.alter_column('projects', 'status_page_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('projects_team_id_fkey', 'projects', type_='foreignkey')
    op.alter_column('team_invites', 'accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('team_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('team_invites_team_id_fkey', 'team_invites', type_='foreignkey')
    op.create_foreign_key(None, 'team_invites', 'teams', ['team_id'], ['id'])
    op.alter_column('team_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('team_members_team_id_user_id_key', 'team_members', type_='unique')
    op.drop_constraint('team_members_user_id_fkey', 'team_members', type_='foreignkey')
    op.drop_constraint('team_members_team_id_fkey', 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'team_members', 'teams', ['team_id'], ['id'])
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('uptime_checks', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_uptime_checks_checked_at', table_name='uptime_checks')
    op.drop_index('idx_uptime_checks_monitor_id', table_name='uptime_checks')
    op.drop_constraint('uptime_checks_monitor_id_fkey', 'uptime_checks', type_='foreignkey')
    op.alter_column('uptime_monitors', 'method',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("'GET'::character varying"))
    op.alter_column('uptime_monitors', 'interval_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('60'))
    op.alter_column('uptime_monitors', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('uptime_monitors', 'expected_status',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('200'))
    op.alter_column('uptime_monitors', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('uptime_monitors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('users', 'notify_email',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'notify_alerts',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'notify_alerts',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'notify_email',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('uptime_monitors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('uptime_monitors', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('uptime_monitors', 'expected_status',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('200'))
    op.alter_column('uptime_monitors', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('uptime_monitors', 'interval_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('60'))
    op.alter_column('uptime_monitors', 'method',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("'GET'::character varying"))
    op.create_foreign_key('uptime_checks_monitor_id_fkey', 'uptime_checks', 'uptime_monitors', ['monitor_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_uptime_checks_monitor_id', 'uptime_checks', ['monitor_id'], unique=False)
    op.create_index('idx_uptime_checks_checked_at', 'uptime_checks', ['checked_at'], unique=False)
    op.alter_column('uptime_checks', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key('team_members_team_id_fkey', 'team_members', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('team_members_user_id_fkey', 'team_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('team_members_team_id_user_id_key', 'team_members', ['team_id', 'user_id'])
    op.alter_column('team_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'team_invites', type_='foreignkey')
    op.create_foreign_key('team_invites_team_id_fkey', 'team_invites', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.alter_column('team_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_invites', 'accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_foreign_key('projects_team_id_fkey', 'projects', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.alter_column('projects', 'status_page_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index('ix_ai_insights_project_id', 'ai_insights', ['project_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
