"""add email verification fields

Revision ID: 7464d63c99bd
Revises: 5fdccd28bb65
Create Date: 2026-05-18 13:52:43.697558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7464d63c99bd'
down_revision: Union[str, None] = '5fdccd28bb65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('verification_token', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
